# 容器的端口号
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  # 热部署
  devtools:
    restart:
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
  # mvc的jsp路径
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
    static-path-pattern: /**
  # 编码
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # elasticsearch , 9300 是 Java 客户端的端口(tcp)。9200 是支持 Restful HTTP 
##  data:
##    elasticsearch:
      # 集群名字
##      cluster-name: ray
##      cluster-nodes: 192.168.192.129:9300
##      repositories: 
        #开启 Elasticsearch 仓库
##        enabled: true
  mail:  
    host: smtp.lenovoeduonline.com
    username: information@lenovoeduonline.com
    password: lenovo*123
    properties:  
      mail:  
        smtp: 
          auth: true
          starttls: 
            enable: true
            required: true
            
# 日志配置
logging:
  config: classpath:log4j2.yml